<a href="https://colab.research.google.com/github/AdityaWarrier2006/TensorFlow-for-Machine-Learning/blob/main/01_03_neural_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###A larger example

Preprocessing data

In [1]:
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd

In [2]:
insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv")
insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

# create a column transformer
ct = make_column_transformer(
    (MinMaxScaler(), ["age", "bmi", "children"]), # turn all values btwn 0 and 1
    (OneHotEncoder(handle_unknown="ignore"), ["sex", "smoker", "region"])
)

# create x, y
x = insurance.drop("charges", axis=1)
y = insurance["charges"]

# Build our train and test
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)

# fit the column transformer to our training
ct.fit(x_train)

# transform training and test data with normalization (MinMaxScaler) and OneHotEncoder
x_train_normal = ct.transform(x_train)
x_test_normal = ct.transform(x_test)

In [4]:
# what does the data look like now
x_train.loc[0] # before transforming

age                19
sex            female
bmi              27.9
children            0
smoker            yes
region      southwest
Name: 0, dtype: object

In [5]:
x_train_normal[0]

array([0.5       , 0.56873823, 0.4       , 1.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       1.        ])

In [6]:
x_train_normal[19]

array([0.06521739, 0.1661286 , 0.        , 1.        , 0.        ,
       1.        , 0.        , 1.        , 0.        , 0.        ,
       0.        ])

In [7]:
x_train.shape, x_train_normal.shape

((1070, 6), (1070, 11))

Create the model

In [8]:
insurance_model = tf.keras.Sequential([
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

insurance_model.compile(loss = ["mae"],
                optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01),
                metrics = ["mae"])

insurance_model.fit(x_train_normal, y_train, epochs = 100, verbose = 0)

In [9]:
# eval the model
# there will be a reduction in mae purely because the training data is normalised
# with normalisation we get a faster convergence time. ie. better result with less epochs

insurance_model.evaluate(x_test_normal, y_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3655.1377 - mae: 3655.1377

[3655.1376953125, 3655.1376953125]